---
title: "Conditional Logit vs. Log-linear Models for Group-Level Assortative Mating"
description: "The second note in the series. Here I estimate and compare parameter estimates from conditional logit, multinomial logit, and loglinear models of two-way contingency tables (or data that can be reduced to such a table)."
date: "2026-08-27T16:00:00+02:00"
author: "Benjamin F. Jarvis"
metadata-files:
  - ../_post-defaults.yml
categories:
  - "matching"
  - "conditional logit"
  - "loglinear models"
  - "assortative mating"
draft: false
---

## Introduction

This is part 2 in the series discussing how and why to use conditional logistic regression models for assortative mating research. The goal of this post is to convince you that conditional logistic regression can provide the same answers to questions typically answered using log-linear models. I do so not through mathematical argument, which is already covered pretty well by Breen [-@breenIndividualLevelModels1994] and Logan [-@loganMultivariateModelMobility1983]. Instead, I just fit mathematically equivalent models to simulated data and demonstrate, not only that key parameters and their standard errors are the same, but also how to handle what is, for most people, the most daunting part of fitting a clogit model: building the correct data structure.

To do so, I use a generator function 

```{r}
getwd()
source("./simulate_marriage_market.R")
```

